name: byrd
description: "a app for my mom to keep track of her birds lol"
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  image_picker: ^1.1.2
  intl: ^0.20.2
  uuid: ^4.5.1
  flutter_svg: ^2.0.10
  cupertino_icons: ^1.0.8
  flutter_colorpicker: ^1.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  assets:
    - assets/icons/duck.svg
    - assets/icons/goose.svg
    - assets/icons/turkey.svg
    - assets/icons/other.svg
  uses-material-design: true

